### ISSUE TITLE
Should ignore .setting, build folder and etc.

### ISSUE THREAD

**Issue by Onionz** [test-alexa/test#1]
You should create .gitignore file to exclude build, .project, .classpath and .setting folder. But before you do these, you should push a new commit with those folder removed.

**Comment by Onionz** [comment]
Dont commit any generated files like `build/**` or `war` files. These files vary from different computers.

**Comment by allenhxy12** [comment]
fd5fa1df3ef3b8a2af5c4ba6a3ed7b500f37f07a

resolved?

**Comment by allenhxy12** [comment]
589a9fdc51a6f952978486197edf57b68ba9111a

2nd try
